BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'vertical'
        size_hint_y: 0.8
        Button:
            text: 'product type'
        Button:
            text: 'product type'
        Button:
            text: 'product type'
    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: 0.2
        Label:
            text: "Total Price"
        Button:
            text: 'Reset'
            background_color: 'yellow'